{
    "name": "School Management System",
    "author": "Vivek",
    "version": "18.0",
    "license": "LGPL-3",
    "depends": ["base", ],

    "data":
        [
            "security/ir.model.access.csv",
            "views/view_driver.xml",
            "views/view_vechicle.xml",
            "views/view_assign_students.xml",
            "views/view_teachers.xml",
            "views/view_parent.xml",
            "views/view_accountant.xml",
            "views/librarian.xml",
            "views/events.xml",
            "views/galleryviews.xml",
            "views/alumini_manage.xml",
            "views/view_admission.xml",
            "views/bulk_admission.xml",
            "views/views_class.xml",
            "views/view_academic_room.xml",
            "views/academic_department.xml",
            "views/view_subject.xml",
            "views/routine.xml",
            "views/timetable.xml",
            "views/view_book_list.xml",
            "views/noticeboard.xml",
            "views/subjectlines.xml",
            "views/exam.xml",
            "views/View_student.xml",
            "views/menu.xml", ],
}
